updated the highlight  (#10635)
* updated the highlight logic to also highlight children of the selected object

* removed the ts ignore

* Updated var name from "test"
Put the ts ignore back since it is still throwing an error "../spatial/src/renderer/components/HighlightComponent.ts(53,24): error TS2339: Property 'OutlineEffect' does not exist on type 'EffectComposer'."

* removed the ts ignore and changed the array to a set type

* Re-export postprocessing

* moved the hardcoded values to the highlight state

* added check for if the effect composer exists or not
and exclude non visible entities
changed let to be a const

---------

Co-authored-by: Michael Estes <michael@etherealengine.com>