Updated var name from "test" Put the ts ignore back since it is still throwing an error "../spatial/src/renderer/components/HighlightComponent.ts(53,24): error TS2339: Property 'OutlineEffect' does not exist on type 'EffectComposer'."